# Generated by Django 3.0.7 on 2020-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckarsSite',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('_id', models.IntegerField()),
                ('mlid', models.IntegerField()),
                ('precio', models.FloatField()),
                ('kilometros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeliItem',
            fields=[
                ('mlid', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('precio', models.FloatField()),
                ('kilometros', models.IntegerField()),
                ('seller_id', models.IntegerField()),
            ],
        ),
    ]
