# Generated by Django 3.0.7 on 2020-06-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkarssite',
            name='_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkarssite',
            name='mlid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meliitem',
            name='mlid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
