# Generated by Django 3.0.7 on 2020-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200616_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckarsSiteByID',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('kilometros', models.IntegerField()),
            ],
        ),
    ]
