# Generated by Django 3.0.7 on 2020-06-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_checkarssitebyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkarssite',
            name='kilometros',
        ),
        migrations.RemoveField(
            model_name='checkarssite',
            name='precio',
        ),
    ]
